### ISSUE TITLE
No `github.event.release.latest` 

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/action-wp-pronamic-directory-plugin-deploy#1]
Currently we have lot of configs like this with `${{ inputs.latest || github.event.release.latest }}`:

```yml
name: Deploy to Pronamic WordPress directory

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy to Pronamic WordPress directory'
        required: true
        type: string
      latest:
        default: true
        type: boolean
        description: 'Deploy as "Latest"'
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Pronamic WordPress directory
      url: https://wp.pronamic.directory/plugins/pronamic-cloudflare/

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Deploy
        uses: pronamic/action-wp-pronamic-directory-plugin-deploy@main
        with:
          username: ${{ vars.WP_PRONAMIC_DIRECTORY_USERNAME }}
          password: ${{ secrets.WP_PRONAMIC_DIRECTORY_PASSWORD }}
          slug: pronamic-cloudflare
          tag: ${{ inputs.tag || github.event.release.tag_name }}
          latest: ${{ inputs.latest || github.event.release.latest }}
```

https://github.com/pronamic/wp-pronamic-cloudflare/blob/8efe216120cbe3f6e4ef5440e4ab6a9ae60c1daf/.github/workflows/deploy-to-wp-pronamic-directory.yml#L29-L37

The `github.event.release.latest` however is not available, i have made this up 😏

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs

There is a GitHub latest release API:
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release

And we can use GitHub CLI for this:

```
gh repo view --json latestRelease -q .latestRelease.tagName
```

There are also existing GitHub actions available:
https://github.com/marketplace?query=latest+release

What is the nicest way to check if we are dealing with the latest release?

CC @rvdsteege

**Comment by rvdsteege** [comment]
I was thinking something along these lines (untested 🤖 code):

```yaml
      - name: Determine if latest release
        if: ${{ github.event_name == 'release' }}
        run: |
          latest_release=$(gh repo view --json latestRelease -q '.latestRelease.tagName')
          current_tag="${{ github.event.release.tag_name }}"
          echo "IS_LATEST_RELEASE=$([ "$latest_release" = "$current_tag" ] && echo true || echo false)" >> $GITHUB_ENV
      - name: Deploy
        uses: pronamic/action-wp-pronamic-directory-plugin-deploy@main
        with:
          username: ${{ vars.WP_PRONAMIC_DIRECTORY_USERNAME }}
          password: ${{ secrets.WP_PRONAMIC_DIRECTORY_PASSWORD }}
          slug: pronamic-cloudflare
          tag: ${{ github.event.release.tag_name }}
          latest: ${{ inputs.latest || env.IS_LATEST_RELEASE }}
```
